stages:
  - build
  - deploy

variables:
  STAG_IO_K8S_API: ${STAG_IO_K8S_API_PREFIX}/apis/apps/v1/namespaces/default/deployments/xpressreal-wiki
  STAG_COM_K8S_API: ${STAG_COM_K8S_API_PREFIX}/apis/apps/v1/namespaces/default/deployments/xpressreal-wiki
  PROD_IO_K8S_API: ${PROD_IO_K8S_API_PREFIX}/apis/apps/v1/namespaces/default/deployments/xpressreal-wiki
  PROD_COM_K8S_API: ${PROD_COM_K8S_API_PREFIX}/apis/apps/v1/namespaces/default/deployments/xpressreal-wiki
  IMAGE: ${IMAGE_REGISTRY_COM}/fydeos/xpressreal-wiki
  IMAGE_IO: ${IMAGE_REGISTRY_IO}/fydeos/xpressreal-wiki

build:
  stage: build
  tags:
    - shell
  before_script:
    - export ENV=$(echo $CI_COMMIT_TAG | cut -d'-' -f1)
    - export VERSION=$(echo $CI_COMMIT_TAG | cut -d'-' -f2)
    - export DOCKER_CMD="docker"
  script:
    - if [[ "$(${DOCKER_CMD} pull -q ${IMAGE}:${VERSION} 2> /dev/null)" == "" ]]; then ${DOCKER_CMD} build . -f Dockerfile -t ${IMAGE}:${VERSION}; fi
    - ${DOCKER_CMD} tag ${IMAGE}:${VERSION} ${IMAGE}:${ENV}-latest
    - ${DOCKER_CMD} push ${IMAGE}:${VERSION}
    - ${DOCKER_CMD} push ${IMAGE}:${ENV}-latest
    - ${DOCKER_CMD} tag ${IMAGE}:${VERSION} ${IMAGE_IO}:${VERSION}
    - ${DOCKER_CMD} tag ${IMAGE_IO}:${VERSION} ${IMAGE_IO}:${ENV}-latest
    - ${DOCKER_CMD} push ${IMAGE_IO}:${VERSION}
    - ${DOCKER_CMD} push ${IMAGE_IO}:${ENV}-latest
  only:
    - /^prod-.*$/
    - /^stag-.*$/

deploy-prod:
  stage: deploy
  tags:
    - shell
  before_script:
    - export VERSION=$(echo $CI_COMMIT_TAG | cut -d'-' -f2)
  script:
    - curl -X PATCH -u "${NEW_DEPLOY_TOKEN}" -H "Content-Type:application/json-patch+json" -d "[{\"op\":\"replace\",\"path\":\"/spec/template/spec/containers/0/image\",\"value\":\"${IMAGE}:${VERSION}\"}]" "${PROD_COM_K8S_API}"
    - curl -X PATCH -u "${NEW_DEPLOY_TOKEN}" -H "Content-Type:application/json-patch+json" -d "[{\"op\":\"replace\",\"path\":\"/spec/template/spec/containers/0/image\",\"value\":\"${IMAGE_IO}:${VERSION}\"}]" "${PROD_IO_K8S_API}"
  only:
    - /^prod-.*$/

deploy-stag:
  stage: deploy
  tags:
    - shell
  before_script:
    - export VERSION=$(echo $CI_COMMIT_TAG | cut -d'-' -f2)
  script:
    - curl -X PATCH -u "${NEW_DEPLOY_TOKEN}" -H "Content-Type:application/json-patch+json" -d "[{\"op\":\"replace\",\"path\":\"/spec/template/spec/containers/0/image\",\"value\":\"${IMAGE}:${VERSION}\"}]" "${STAG_COM_K8S_API}"
    - curl -X PATCH -u "${NEW_DEPLOY_TOKEN}" -H "Content-Type:application/json-patch+json" -d "[{\"op\":\"replace\",\"path\":\"/spec/template/spec/containers/0/image\",\"value\":\"${IMAGE_IO}:${VERSION}\"}]" "${STAG_IO_K8S_API}"
  only:
    - /^stag-.*$/
